### ISSUE TITLE
PVector.prototype.distSq(vector) does not take Z values into account

### ISSUE THREAD

**Issue by DriesCruyskens** [MAKIO135/pvectorjs#10]
Hello, I use pvectorjs in my generative sketches but after encountering weird bugs using `PVector.prototype.distSq(vector)` I noticed no Z-values are used in the calculation:

https://github.com/MAKIO135/pvectorjs/blob/130838690e84cb9f8b2c80d7b83db060a56362d3/index.js#L383-L385

The reason the test succeeded is because the manual squared distance calculation is wrong. For:
`v1 = new PVector(100, 50, 30)`
`v2 = new PVector(200, 60, 20)`
(200-100)^2 + (60-50)^2 + (20-30)^2 = **10200** instead of 10100.

https://github.com/MAKIO135/pvectorjs/blob/130838690e84cb9f8b2c80d7b83db060a56362d3/test/pvector.js#L1517-L1533

**Solution:** 
Changing tested value to correct one and adding Z-values in squared distance formula.

**Comment by DriesCruyskens** [comment]
Took the liberty to fix it and create a pull request.

**Comment by MAKIO135** [comment]
Ho thanks ! 🙏  
Sorry for not answering sooner, notifications were turned off. Thanks for your PRs right now !
(Would love to see your generetaive experiments with PVectorjs 😉)
