### ISSUE TITLE
Bug: Cross product

### ISSUE THREAD

**Issue by exodus4d** [MAKIO135/pvectorjs#22]
Your implementation of `cross()` is wrong:

 https://github.com/MAKIO135/pvectorjs/blob/35c68d1dbed4465880bc5548c2d92448a738c322/index.js#L364-L369

If you change `this.x` in the first line to a new value. The calculation for `this.y` (2nd line)  takes the new `this.x` rather than the the orig.  `this.x`... 3rd line is now calculated from two wrong values (`this.x` and `this.y`) rather than the orig. values....

The test for `cross()` expects the wrong result, too. 😱 
https://github.com/MAKIO135/pvectorjs/blob/35c68d1dbed4465880bc5548c2d92448a738c322/test/pvector.js#L1389-L1405

```js
{x: 10, y: 20, z: 2} • {x: 60, y: 80, z: 6} = {x: -40, y: 360, z: -24800} // BUG
{x: 10, y: 20, z: 2} • {x: 60, y: 80, z: 6} = {x: -40, y: 60,  z: -400}   // OK
```

This will fix it:
```js
function(vec) {
    const x = this.y * vec.z - vec.y * this.z
    const y = this.z * vec.x - vec.z * this.x
    const z = this.x * vec.y - vec.x * this.y
    this.x = x;
    this.y = y;
    this.z = z;
    return this
}
```

**Comment by MAKIO135** [comment]
Ho! thanks a lot! 🙏
Don't know why I had not seen your issue sooner 🤔
